name: bhartee-ai-interviewer-demo
region: nyc
services:
  - name: web
    github:
      repo: sahiljagtap08/main-calhacks-bhartee
      branch: main
    build_command: pip install -r requirements.txt
    run_command: reflex run --env prod
    envs:
      - key: CLERK_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${CLERK_PUBLISHABLE_KEY}
      - key: CLERK_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${CLERK_SECRET_KEY}
      - key: JDOODLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        value: ${JDOODLE_CLIENT_ID}
      - key: JDOODLE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JDOODLE_CLIENT_SECRET}
      - key: SINGLESTORE_CONNECTION_STRING
        scope: RUN_AND_BUILD_TIME
        value: ${SINGLESTORE_CONNECTION_STRING}
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${GROQ_API_KEY}
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
domains:
  - domain: prototype.bhartee.ai
    type: PRIMARY
static_sites:
  - name: frontend
    github:
      repo: sahiljagtap08/main-calhacks-bhartee
      branch: main
    build_command: reflex export --frontend-only
    output_dir: frontend/.web
    routes:
      - path: /static